# Generated by Django 5.2.3 on 2025-06-23 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onepass', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='onepass_text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_data', models.TextField()),
            ],
        ),
    ]
