# Generated by Django 5.2.3 on 2025-06-23 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onepass', '0002_onepass_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='onepass_text',
            name='user_name',
            field=models.CharField(default='<user_name>', max_length=64),
        ),
        migrations.AlterField(
            model_name='onepass_text',
            name='user_data',
            field=models.TextField(default='<user_data>'),
        ),
    ]
